name: Release
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - olympus-api-released
      -
permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # to be able to publish a GitHub release
      contents: write
      # to be able to comment on released issues
      issues: write
      # to be able to comment on released pull requests
      pull-requests: write
      # to enable use of OIDC for npm provenance
      id-token: write
      # to publish NPM packages
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@ncfritz:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Update olympus-api
        if: github.event_name == 'repository_dispatch'
        run: |
          npm install @ncfritz/olympus-api@${{ github.event.client_payload.version }}

          - name: Commit dependency update
            if: github.event_name == 'repository_dispatch'
            run: |
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

              git add package.json package-lock.json

              if ! git diff --cached --quiet; then
                git commit -m "chore(deps): update @ncfritz/olympus-api [skip ci]"
                git push
              fi
      - name: Install dependencies
        run: npm clean-install
      - name: Verify installed dependencies
        run: npm audit signatures
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release