- '!include minerva_meeting_day_statistics.yaml'
- '!include minerva_meeting_hour_statistics.yaml'
- '!include minerva_meeting_status_statistics.yaml'
- '!include minerva_notes_hour_statistics.yaml'
- '!include minerva_notes_type_statistics.yaml'
