table:
  name: tv_series_content_ratings
  schema: dionysus
configuration:
  column_config:
    certification_type:
      custom_name: type
    created_at:
      custom_name: createdTime
    iso_3166_1:
      custom_name: country
    rating:
      custom_name: rating
    series_id:
      custom_name: seriesId
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    certification_type: type
    created_at: createdTime
    iso_3166_1: country
    rating: rating
    series_id: seriesId
    updated_at: lastUpdatedTime
  custom_root_fields: {}
object_relationships:
- name: certification
  using:
    manual_configuration:
      column_mapping:
        certification_type: type
        iso_3166_1: country
        rating: certification
      insertion_order: null
      remote_table:
        name: certifications
        schema: dionysus
