table:
  name: metadata_workflow
  schema: dionysus
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    finished_at:
      custom_name: finishedTime
    started_at:
      custom_name: startedTime
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    created_at: createdTime
    finished_at: finishedTime
    started_at: startedTime
    updated_at: lastUpdatedTime
  custom_root_fields: {}
array_relationships:
- name: steps
  using:
    manual_configuration:
      column_mapping:
        id: workflow_id
      insertion_order: null
      remote_table:
        name: metadata_workflow_step
        schema: dionysus
