table:
  name: metadata_workflow_status_statistics
  schema: dionysus
configuration:
  column_config:
    created_date:
      custom_name: createdTime
  custom_column_names:
    created_date: createdTime
  custom_root_fields: {}
