table:
  name: tv_season_crew_jobs
  schema: dionysus
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    credit_id:
      custom_name: creditId
    episode_count:
      custom_name: episodeCount
    person_id:
      custom_name: personId
    season_id:
      custom_name: seasonId
    series_id:
      custom_name: seriesId
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    created_at: createdTime
    credit_id: creditId
    episode_count: episodeCount
    person_id: personId
    season_id: seasonId
    series_id: seriesId
    updated_at: lastUpdatedTime
  custom_root_fields: {}
