table:
  name: tv_series_keywords
  schema: dionysus
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    keyword_id:
      custom_name: keywordId
    series_id:
      custom_name: seriesId
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    created_at: createdTime
    keyword_id: keywordId
    series_id: seriesId
    updated_at: lastUpdatedTime
  custom_root_fields: {}
object_relationships:
- name: keyword
  using:
    manual_configuration:
      column_mapping:
        keyword_id: id
      insertion_order: null
      remote_table:
        name: keywords
        schema: dionysus
