table:
  name: tv_episodes
  schema: dionysus
configuration:
  column_config:
    air_date:
      custom_name: airDate
    created_at:
      custom_name: createdTime
    episode_number:
      custom_name: episodeNumber
    media_type:
      custom_name: mediaType
    production_code:
      custom_name: productionCode
    season_id:
      custom_name: seasonId
    season_number:
      custom_name: seasonNumber
    series_id:
      custom_name: seriesId
    still_path:
      custom_name: stillPath
    updated_at:
      custom_name: lastUpdatedTime
    vote_average:
      custom_name: voteAverage
    vote_count:
      custom_name: voteCount
  custom_column_names:
    air_date: airDate
    created_at: createdTime
    episode_number: episodeNumber
    media_type: mediaType
    production_code: productionCode
    season_id: seasonId
    season_number: seasonNumber
    series_id: seriesId
    still_path: stillPath
    updated_at: lastUpdatedTime
    vote_average: voteAverage
    vote_count: voteCount
  custom_root_fields: {}
object_relationships:
- name: asset
  using:
    manual_configuration:
      column_mapping:
        id: media_id
        media_type: asset_type
      insertion_order: null
      remote_table:
        name: media_asset
        schema: dionysus
- name: favorite
  using:
    manual_configuration:
      column_mapping:
        id: media_id
        media_type: type
      insertion_order: null
      remote_table:
        name: media_favorite
        schema: dionysus
- name: searchConfiguration
  using:
    manual_configuration:
      column_mapping:
        id: media_id
        media_type: asset_type
      insertion_order: null
      remote_table:
        name: media_asset_search_configuration
        schema: dionysus
- name: season
  using:
    manual_configuration:
      column_mapping:
        season_number: season_number
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_seasons
        schema: dionysus
- name: series
  using:
    manual_configuration:
      column_mapping:
        series_id: id
      insertion_order: null
      remote_table:
        name: tv_series
        schema: dionysus
array_relationships:
- name: cast
  using:
    manual_configuration:
      column_mapping:
        id: episode_id
        season_id: season_id
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_episode_cast
        schema: dionysus
- name: crew
  using:
    manual_configuration:
      column_mapping:
        id: episode_id
        season_id: season_id
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_episode_crew
        schema: dionysus
- name: externalIds
  using:
    manual_configuration:
      column_mapping:
        id: episode_id
        season_id: season_id
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_episode_external_ids
        schema: dionysus
- name: guestStars
  using:
    manual_configuration:
      column_mapping:
        id: episode_id
        season_id: season_id
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_episode_guest_stars
        schema: dionysus
- name: images
  using:
    manual_configuration:
      column_mapping:
        id: episode_id
        season_id: season_id
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_episode_images
        schema: dionysus
- name: searchResults
  using:
    manual_configuration:
      column_mapping:
        id: media_id
        media_type: asset_type
      insertion_order: null
      remote_table:
        name: media_asset_search_result
        schema: dionysus
- name: videos
  using:
    manual_configuration:
      column_mapping:
        id: episode_id
        season_id: season_id
        series_id: series_id
      insertion_order: null
      remote_table:
        name: tv_episode_videos
        schema: dionysus
