table:
  name: movie_spoken_languages
  schema: dionysus
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    language_id:
      custom_name: languageCode
    movie_id:
      custom_name: movieId
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    created_at: createdTime
    language_id: languageCode
    movie_id: movieId
    updated_at: lastUpdatedTime
  custom_root_fields: {}
object_relationships:
- name: language
  using:
    manual_configuration:
      column_mapping:
        language_id: id
      insertion_order: null
      remote_table:
        name: languages
        schema: dionysus
- name: movie
  using:
    manual_configuration:
      column_mapping:
        movie_id: id
      insertion_order: null
      remote_table:
        name: movies
        schema: dionysus
