table:
  name: movie_videos
  schema: dionysus
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    iso_3166_1:
      custom_name: countryCode
    iso_639_1:
      custom_name: languageCode
    published_at:
      custom_name: publishedDate
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    created_at: createdTime
    iso_3166_1: countryCode
    iso_639_1: languageCode
    published_at: publishedDate
    updated_at: lastUpdatedTime
  custom_root_fields: {}
object_relationships:
- name: country
  using:
    manual_configuration:
      column_mapping:
        iso_3166_1: id
      insertion_order: null
      remote_table:
        name: countries
        schema: dionysus
- name: language
  using:
    manual_configuration:
      column_mapping:
        iso_639_1: id
      insertion_order: null
      remote_table:
        name: languages
        schema: dionysus
