table:
  name: movie_recommendations
  schema: dionysus
configuration:
  column_config:
    recommendation_id:
      custom_name: recommendationId
  custom_column_names:
    recommendation_id: recommendationId
  custom_root_fields: {}
object_relationships:
- name: movie
  using:
    manual_configuration:
      column_mapping:
        recommendation_id: id
      insertion_order: null
      remote_table:
        name: movies
        schema: dionysus
