table:
  name: mail_accounts
  schema: minerva
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    updated_at:
      custom_name: lastUpdatedTime
    user_id:
      custom_name: userId
    verification_method:
      custom_name: verificationMethod
    verified_at:
      custom_name: verifiedTime
  custom_column_names:
    created_at: createdTime
    updated_at: lastUpdatedTime
    user_id: userId
    verification_method: verificationMethod
    verified_at: verifiedTime
  custom_root_fields: {}
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: labels
    using:
      foreign_key_constraint_on:
        column: account_id
        table:
          name: mail_labels
          schema: minerva
  - name: messages
    using:
      foreign_key_constraint_on:
        column: account_id
        table:
          name: mail_messages
          schema: minerva
