table:
  name: goal_checkins
  schema: minerva
configuration:
  column_config:
    checkin_date:
      custom_name: checkinDate
    created_at:
      custom_name: createdTime
    goal_id:
      custom_name: goalId
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    checkin_date: checkinDate
    created_at: createdTime
    goal_id: goalId
    updated_at: lastUpdatedTime
  custom_root_fields: {}
object_relationships:
  - name: goal
    using:
      foreign_key_constraint_on: goal_id
