table:
  name: reviews
  schema: minerva
configuration:
  column_config:
    completed_at:
      custom_name: completedTime
    created_at:
      custom_name: createdTime
    period_start:
      custom_name: periodStart
    updated_at:
      custom_name: lastUpdatedTime
    user_id:
      custom_name: userId
  custom_column_names:
    completed_at: completedTime
    created_at: createdTime
    period_start: periodStart
    updated_at: lastUpdatedTime
    user_id: userId
  custom_root_fields: {}
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: answers
    using:
      manual_configuration:
        column_mapping:
          id: review_id
        insertion_order: null
        remote_table:
          name: review_answers
          schema: minerva
  - name: items
    using:
      manual_configuration:
        column_mapping:
          id: review_id
        insertion_order: null
        remote_table:
          name: review_items
          schema: minerva
  - name: pins
    using:
      manual_configuration:
        column_mapping:
          id: review_id
        insertion_order: null
        remote_table:
          name: review_pins
          schema: minerva
