table:
  name: mail_account_connections
  schema: minerva
configuration:
  column_config:
    account_id:
      custom_name: accountId
    code_verifier:
      custom_name: codeVerifier
    completed_at:
      custom_name: completedTime
    created_at:
      custom_name: createdTime
    expires_at:
      custom_name: expiresTime
    return_to:
      custom_name: returnTo
    state_hash:
      custom_name: stateHash
    updated_at:
      custom_name: lastUpdatedTime
    user_id:
      custom_name: userId
  custom_column_names:
    account_id: accountId
    code_verifier: codeVerifier
    completed_at: completedTime
    created_at: createdTime
    expires_at: expiresTime
    return_to: returnTo
    state_hash: stateHash
    updated_at: lastUpdatedTime
    user_id: userId
  custom_root_fields: {}
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
