table:
  name: mail_decisions
  schema: minerva
configuration:
  column_config:
    account_id:
      custom_name: accountId
    batch_id:
      custom_name: batchId
    created_at:
      custom_name: createdTime
    decided_at:
      custom_name: decidedTime
    label_id:
      custom_name: labelId
    message_id:
      custom_name: messageId
    updated_at:
      custom_name: lastUpdatedTime
    user_id:
      custom_name: userId
  custom_column_names:
    account_id: accountId
    batch_id: batchId
    created_at: createdTime
    decided_at: decidedTime
    label_id: labelId
    message_id: messageId
    updated_at: lastUpdatedTime
    user_id: userId
  custom_root_fields: {}
object_relationships:
  - name: batch
    using:
      foreign_key_constraint_on: batch_id
  - name: label
    using:
      foreign_key_constraint_on: label_id
  - name: message
    using:
      foreign_key_constraint_on: message_id
