table:
  name: mail_labels
  schema: minerva
configuration:
  column_config:
    account_id:
      custom_name: accountId
    created_at:
      custom_name: createdTime
    gmail_label_id:
      custom_name: gmailLabelId
    parent_name:
      custom_name: parentName
    updated_at:
      custom_name: lastUpdatedTime
  custom_column_names:
    account_id: accountId
    created_at: createdTime
    gmail_label_id: gmailLabelId
    parent_name: parentName
    updated_at: lastUpdatedTime
  custom_root_fields: {}
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
array_relationships:
  - name: messageLabels
    using:
      foreign_key_constraint_on:
        column: label_id
        table:
          name: mail_message_labels
          schema: minerva
