table:
  name: user_identities
  schema: olympus
configuration:
  column_config:
    created_at:
      custom_name: createdTime
    updated_at:
      custom_name: lastUpdatedTime
    user_id:
      custom_name: userId
  custom_column_names:
    created_at: createdTime
    updated_at: lastUpdatedTime
    user_id: userId
  custom_root_fields: {}
object_relationships:
  - name: user
    using:
      foreign_key_constraint_on: user_id
