/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsController_listOverrides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{source}/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{source}/{uid}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventsController_getOverride"];
        put: operations["EventsController_setOverride"];
        post?: never;
        delete: operations["EventsController_clearOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CalendarsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendars/{calendarId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CalendarsController_triggerSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/freebusy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AvailabilityController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OverridesController_list"];
        put?: never;
        post: operations["OverridesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overrides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["OverridesController_updateStatus"];
        post?: never;
        delete: operations["OverridesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CurrentUserDto: {
            email: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        AccessTokenDto: {
            accessToken: string;
        };
        EventResponseDto: {
            id: string;
            subject: string;
            /** @enum {string} */
            sensitivity: "normal" | "personal" | "private" | "confidential";
            /** @enum {string} */
            importance: "low" | "normal" | "high";
            /** @enum {string} */
            occurrenceType: "single" | "occurrence" | "series_master";
            /** @enum {string} */
            type: "appointment" | "meeting" | "other";
            reminder: boolean;
            /** @enum {string} */
            response: "organizer" | "accepted" | "declined" | "tentative" | "needs_action";
            /** @description ISO-8601 */
            startTime: string;
            /** @description ISO-8601 */
            endTime: string;
            /** @description Minutes */
            duration: number;
            allDay: boolean;
            /** @enum {string} */
            status: "free" | "busy" | "tentative" | "out_of_office" | "working_elsewhere";
            location?: string | null;
            cancelled: boolean;
            organizerEmail?: string | null;
            /** @description Soft-delete flag */
            deleted: boolean;
            uid: string;
            recurrenceId?: string | null;
            source: string;
        };
        EventOverrideResponseDto: {
            eventId: string;
            /** @enum {string} */
            status: "none" | "free" | "interruptable" | "busy";
        };
        SetEventOverrideDto: {
            /** @enum {string} */
            status: "none" | "free" | "interruptable" | "busy";
        };
        CalendarStatusDto: {
            /** @description Which CalendarProvider implementation this calendar uses */
            provider: string;
            /** @description Which stored OAuth credential this calendar authorizes with */
            accountLabel: string;
            /** @description The provider's own calendar id */
            calendarId: string;
            /** @description The source label written onto this calendar's event rows */
            source: string;
            /** @description True once at least one full sync has completed */
            synced: boolean;
            /** @description Whether a Google push notification channel is configured for this calendar */
            enablePush: boolean;
        };
        AvailabilitySlotDto: {
            /** @description ISO-8601 */
            startTime: string;
            /** @description ISO-8601 */
            endTime: string;
            /** @enum {string} */
            status: "none" | "free" | "interruptable" | "busy";
        };
        CreateOverrideBlockDto: {
            /** @description ISO-8601 */
            startTime: string;
            /** @description ISO-8601 */
            endTime: string;
            /** @enum {string} */
            status: "none" | "free" | "interruptable" | "busy";
            label?: string | null;
        };
        OverrideBlockResponseDto: {
            id: string;
            /** @description ISO-8601 */
            startTime: string;
            /** @description ISO-8601 */
            endTime: string;
            /** @enum {string} */
            status: "none" | "free" | "interruptable" | "busy";
            label?: string | null;
        };
        UpdateOverrideBlockStatusDto: {
            /** @enum {string} */
            status: "none" | "free" | "interruptable" | "busy";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The currently authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description A fresh access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_list: {
        parameters: {
            query?: {
                /** @description Filter to events from this configured calendar's source label */
                source?: string;
                /** @description ISO-8601 — only events starting at or after this instant */
                startsAfter?: string;
                /** @description ISO-8601 — only events starting at or before this instant */
                startsBefore?: string;
                cancelled?: boolean;
                deleted?: boolean;
                occurrenceType?: "single" | "occurrence" | "series_master";
                limit?: number;
                /** @description Internal event id to page from (exclusive) */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"][];
                };
            };
        };
    };
    EventsController_listOverrides: {
        parameters: {
            query: {
                /** @description Comma-separated canonical event ids to look up overrides for */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOverrideResponseDto"][];
                };
            };
        };
    };
    EventsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponseDto"];
                };
            };
            /** @description No event for that source/uid */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_getOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOverrideResponseDto"];
                };
            };
            /** @description No event for that source/uid, or no override is set for it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_setOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEventOverrideDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOverrideResponseDto"];
                };
            };
            /** @description No event for that source/uid */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_clearOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No event for that source/uid */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CalendarsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarStatusDto"][];
                };
            };
        };
    };
    CalendarsController_triggerSync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calendarId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync triggered — runs in the background */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No configured calendar with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityController_list: {
        parameters: {
            query: {
                /** @description ISO-8601 — inclusive start of the computed range */
                start: string;
                /** @description ISO-8601 — exclusive end of the computed range */
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computed 15-minute availability slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySlotDto"][];
                };
            };
        };
    };
    OverridesController_list: {
        parameters: {
            query: {
                /** @description ISO-8601 — inclusive start of the range to list */
                start: string;
                /** @description ISO-8601 — exclusive end of the range to list */
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideBlockResponseDto"][];
                };
            };
        };
    };
    OverridesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOverrideBlockDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideBlockResponseDto"];
                };
            };
        };
    };
    OverridesController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOverrideBlockStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideBlockResponseDto"];
                };
            };
            /** @description No override block with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverridesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
