import {
  BaseDestinationEvent,
  NotificationContext,
  NotificationType,
  SendNotificationRequest,
  SendNotificationResponse,
  SMTPDestination,
  SMTPDestinationEvent,
  SMTPPayload,
  SMTPPriority,
  SynoChatDestination,
  SynoChatDestinationEvent,
  SynoChatDestinationType,
  SynoChatPayload,
  WebSocketDestination,
  WebSocketDestinationEvent,
  WebSocketNotificationLevel,
  WebSocketPayload,
} from "@ncfritz/olympus-model/dist/notifications";

export type {
  BaseDestinationEvent,
  NotificationContext,
  SendNotificationRequest,
  SendNotificationResponse,
  SMTPDestination,
  SMTPDestinationEvent,
  SMTPPayload,
  SynoChatDestination,
  SynoChatDestinationEvent,
  SynoChatDestinationType,
  SynoChatPayload,
  WebSocketDestination,
  WebSocketDestinationEvent,
  WebSocketPayload,
};
export {
  NotificationType,
  SMTPPriority,
  WebSocketNotificationLevel,
}